### ISSUE TITLE
SyntaxError raised on Anyway::Tracing when in Ruby 2.5

### ISSUE THREAD

**Issue by mt-kelvintaywl** [palkan/anyway_config#69]
Hey there, thanks so much this gem firstly, this was a life-saver tbh 👍 

## What did you do?

the `...` syntax in https://github.com/palkan/anyway_config/blob/master/lib/anyway/tracing.rb#L76-L79 and https://github.com/palkan/anyway_config/blob/master/lib/anyway/tracing.rb#L31-L33 sadly causes SyntaxError on my side on a Ruby 2.5.8 runtime.

IIUC, this argument forwarding syntax seems to be a feature available [only from Ruby 2.7 onwards?](https://github.com/ruby/ruby/blob/v2_7_0/NEWS#other-miscellaneous-changes-)

If so, backwards compatibility for < 2.7 may be broken?

```
`require': /[redacted]/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.0.0/lib/anyway/tracing.rb:33: syntax error, unexpected ..., expecting ')' (SyntaxError)
      def dig(...)
              ^~~
/[redacted]/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.0.0/lib/anyway/tracing.rb:34: syntax error, unexpected ..., expecting ')'
        value.dig(...)
                  ^~~
/[redacted]/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.0.0/lib/anyway/tracing.rb:77: syntax error, unexpected ..., expecting ')'
      def keep_if(...)
                  ^~~
/[redacted]/vendor/bundle/ruby/2.5.0/gems/anyway_config-2.0.0/lib/anyway/tracing.rb:79: syntax error, unexpected ..., expecting ')'
        value.keep_if(...)
                      ^~~

```

## Environment

**Ruby Version:**

`2.5.8`

**Framework Version (Rails, whatever):**

nil

**Anyway Config Version:**

2.0.0

**Comment by palkan** [comment]
Thanks for the report!

Could you please try the most recent version first (2.0.6)?

> If so, backwards compatibility for < 2.7 may be broken?

We use [Ruby Next](https://github.com/ruby-next/ruby-next), the compatible source code should be loaded (smth like `/ruby/2.5.0/gems/anyway_config-2.0.0/lib/.rbnext/2.8/anyway/tracing.rb`).

As I see, the original source file is loaded for some reason, which could be because of one of the following:

- Direct loading of the file (e.g., `require "anyway/tracing"`).
- Pulling the gem from GitHub and using the version without auto-transpiling support (2.0.0 is such version).
- Some other bug we need to investigate)

So, the other question is how do you load the gem? The correct way of loading it is to either call `require 'anyway'` or `require 'anyway_config'`. Otherwise the transpiled files couldn't be loaded.

**Comment by mt-kelvintaywl** [comment]
Hi @palkan,

thank you so much for replying so quickly :)

> We use Ruby Next, the compatible source code should be loaded (smth like /ruby/2.5.0/gems/anyway_config-2.0.0/lib/.rbnext/2.8/anyway/tracing.rb).

Ah, got it, so there is a transpiler involved there... that clears up my confusion indeed!  thank you :)

> So, the other question is how do you load the gem? The correct way of loading it is to either call require 'anyway' or require 'anyway_config'. Otherwise the transpiled files couldn't be loaded.

Yea, this is an odd one.
In the relevant classes I'm using `anyway_config`, I've explicitly:

```rb
require 'anyway_config'
```

I've not loaded the tracing file intentionally anywhere. If it helps, for fuller context:

1. we use rbenv for handling ruby versions but i don't think this should have any impact.
2. this error occured when I run unit tests via `rake`. We use `test-unit` gem.
3. I can somehow still reproduce this even after explicitly setting `'anyway_config', '2.0.6'` in the Gemfile.

Thankfully, we were able to upgrade our Ruby runtime environment to 2.7 so this was somehow resolved :)

It's a weird one, and I think it's very likely an issue on my side, rather than the library itself!
Sorry for the trouble, and thank you for the answers and details. I appreciate it, really 🙇
